Form for User Inputs
zorazrr/software-product-sprint pull request #3
Opened 2022-06-06 05:08 UTC by zorazrr

Wip

2022-06-09 20:04 UTC, emilyzhang242 requested changes
Overall great job!

2022-06-09 20:04 UTC, emilyzhang242 commented on portfolio/src/main/java/com/google/sps/servlets/FormHandlerServlet.java
> +        String forfun = request.getParameter("forfun");
Super nitpick: Common naming convention for javascript is camel case, so "forfun" in this case would be "forFun". This helps with readability!

2022-06-09 20:04 UTC, emilyzhang242 commented on portfolio/src/main/webapp/index.html
> +            ></textarea>
```suggestion
            <label for="message" class="form-label">
                Leave a message for me
            </label>
            <textarea
              class="form-control"
              name="message"
              id="message"
              rows="3"
              placeholder="your message"
              required></textarea>
```

It's nice to keep the closing brackets together. This is probably more optional than strictly required, but helps with readability. Please apply this to all instances here and below.

2022-06-10 00:14 UTC, zorazrr commented on portfolio/src/main/webapp/index.html
> +            ></textarea>
Hi Emily! I believe this is due to auto-formatting from using prettier as a pre-commit hook. Would you recommend getting rid of the hook? Or is there a better work-around?

2022-06-10 18:33 UTC, emilyzhang242 commented on portfolio/src/main/webapp/index.html
> +            ></textarea>
Hmm, is there a way to configure prettier somehow? It seems like it has configs but not sure if you have a way to use them: https://prettier.io/docs/en/configuration.html

if not, I guess it's not a huge deal, but just something to be aware of.

2022-06-10 23:56 UTC, zorazrr commented on portfolio/src/main/webapp/index.html
> +            ></textarea>
I played around with prettier config a bit, but did not work out. I ended up getting rid of prettier pre-commit hook if that's ok (will use the editor's default formatting tool going forward). Will merge this PR.

2022-06-12 18:48 UTC, merged